fields = {
"ID":"id value for tracks (presents only in the test file for the submitting purposes)",
"Label":"string valued observable denoting particle types. Can take values "Electron", "Muon", "Kaon", "Proton", "Pion" and "Ghost". This column is absent in the test file.",
"FlagSpd":"flag (0 or 1), if reconstructed track passes through Spd",
"FlagPrs":"flag (0 or 1), if reconstructed track passes through Prs",
"FlagBrem":"flag (0 or 1), if reconstructed track passes through Brem",
"FlagEcal":"flag (0 or 1), if reconstructed track passes through Ecal",
"FlagHcal":"flag (0 or 1), if reconstructed track passes through Hcal",
"FlagRICH1":"flag (0 or 1), if reconstructed track passes through the first RICH detector",
"FlagRICH2":"flag (0 or 1), if reconstructed track passes through the second RICH detector",
"FlagMuon":"flag (0 or 1), if reconstructed track passes through muon stations (Muon)",
"SpdE":"energy deposit associated to the track in the Spd",
"PrsE":"energy deposit associated to the track in the Prs",
"EcalE":"energy deposit associated to the track in the Hcal",
"HcalE":"energy deposit associated to the track in the Hcal",
"PrsDLLbeElectron":"delta log-likelihood for a particle candidate to be electron using information from Prs",
"BremDLLbeElectron":"delta log-likelihood for a particle candidate to be electron using information from Brem",
"TrackP":"particle momentum",
"TrackPt":"particle transverse momentum",
"TrackNDoFSubdetector1":"number of degrees of freedom for track fit using hits in the tracking sub-detector1",
"TrackQualitySubdetector1":"chi2 quality of the track fit using hits in the tracking sub-detector1",
"TrackNDoFSubdetector2":"number of degrees of freedom for track fit using hits in the tracking sub-detector2",
"TrackQualitySubdetector2":"chi2 quality of the track fit using hits in the tracking sub-detector2",
"TrackNDoF":"number of degrees of freedom for track fit using hits in all tracking sub-detectors",
"TrackQualityPerNDoF":"chi2 quality of the track fit per degree of freedom",
"TrackDistanceToZ":"distance between track and z-axis (beam axis)",
"Calo2dFitQuality":"quality of the 2d fit of the clusters in the calorimeter",
"Calo3dFitQuality":"quality of the 3d fit in the calorimeter with assumption that particle was electron",
"EcalDLLbeElectron":"delta log-likelihood for a particle candidate to be electron using information from Ecal",
"EcalDLLbeMuon":"delta log-likelihood for a particle candidate to be muon using information from Ecal",
"EcalShowerLongitudinalParameter":"longitudinal parameter of Ecal shower",
"HcalDLLbeElectron":"delta log-likelihood for a particle candidate to be electron using information from Hcal",
"HcalDLLbeMuon":"delta log-likelihood for a particle candidate to be using information from Hcal",
"RICHpFlagElectron":"flag (0 or 1) if momentum is greater than threshold for electrons to produce Cherenkov light",
"RICHpFlagProton":"flag (0 or 1) if momentum is greater than threshold for protons to produce Cherenkov light",
"RICHpFlagPion":"flag (0 or 1) if momentum is greater than threshold for pions to produce Cherenkov light",
"RICHpFlagKaon":"flag (0 or 1) if momentum is greater than threshold for kaons to produce Cherenkov light",
"RICHpFlagMuon":"flag (0 or 1) if momentum is greater than threshold for muons to produce Cherenkov light",
"RICH_DLLbeBCK":"delta log-likelihood for a particle candidate to be background using information from RICH",
"RICH_DLLbeKaon":"delta log-likelihood for a particle candidate to be kaon using information from RICH",
"RICH_DLLbeElectron":"delta log-likelihood for a particle candidate to be electron using information from RICH",
"RICH_DLLbeMuon":"delta log-likelihood for a particle candidate to be muon using information from RICH",
"RICH_DLLbeProton":"delta log-likelihood for a particle candidate to be proton using information from RICH",
"MuonFlag":"muon flag (is this track muon) which is determined from muon stations",
"MuonLooseFlag":"muon flag (is this track muon) which is determined from muon stations using looser criteria",
"MuonLLbeBCK":"log-likelihood for a particle candidate to be not muon using information from muon stations",
"MuonLLbeMuon":"log-likelihood for a particle candidate to be muon using information from muon stations",
"DLLelectron":"delta log-likelihood for a particle candidate to be electron using information from all subdetectors",
"DLLmuon":"delta log-likelihood for a particle candidate to be muon using information from all subdetectors",
"DLLkaon":"delta log-likelihood for a particle candidate to be kaon using information from all subdetectors",
"DLLproton":"delta log-likelihood for a particle candidate to be proton using information from all subdetectors",
"GhostProbability":"probability for a particle candidate to be ghost track. This variable is an output of classification model used in the tracking algorithm.",
}
